name: makan_employee
description: makan employee application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  lottie: ^1.4.3
  dio: ^4.0.6
  fluttertoast: ^8.1.1
  flutter_animated_dialog: ^2.0.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  fancy_password_field: ^2.0.0
  cached_network_image: ^3.2.2
  flutter_launcher_icons: ^0.10.0
  awesome_dropdown: ^0.0.4
  intl: ^0.17.0 
  scan: ^1.6.0
  flutter_svg: ^1.1.6
  flutter_staggered_animations: ^1.1.1
  country_code_picker: ^2.0.2
  flutter_widget_from_html: ^0.9.0
  flutter_zoom_drawer: ^3.0.2
  r_scan: ^0.1.6+1

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/splash.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/lottie/


  fonts:
    - family: Poppins_Bold
      fonts:
        - asset: assets/fonts/Poppins_Bold.ttf
    - family: Poppins_Medium
      fonts:
        - asset: assets/fonts/Poppins_Medium.ttf
    - family: Poppins_Regular
      fonts:
        - asset: assets/fonts/Poppins_Regular.ttf
    - family: Poppins_SemiBold
      fonts:
        - asset: assets/fonts/Poppins_SemiBold.ttf
    - family: Iconly-Broken
      fonts:
        - asset: assets/fonts/icons.ttf
        